[SW-1] Implement DI container
AndriyBosik/schema-wizard pull request #1
Opened 2023-10-11 08:04 UTC by AndriyBosik

2023-10-11 17:59 UTC, NikolayProkopchuk approved these changes
To eliminate warnings it is good to add @SuppressWarnings("unchecked") for class casting operations like 
T obj = (T) CACHE.getOrDefault(baseType, new HashMap<>()).get(name);

2023-10-30 14:20 UTC, ivlytvynets requested changes

2023-10-30 14:20 UTC, ivlytvynets commented on src/main/java/com/example/di/DiContainer.java
> +        if (name == null && baseDiMap.size() != 1) {
it would be nice to avoid magic numbers

2023-10-30 14:20 UTC, ivlytvynets commented on src/main/java/com/example/di/DiContainer.java
> +                            "Unable to instantiate dependee of class %s. No unique primary constructor was found. Consider using %s annotation only once!",
let's move string constants into Constants class

2023-10-30 14:20 UTC, ivlytvynets commented on src/main/java/com/example/di/DiContainer.java
> +                        String.format("Unable to instantiate dependee. Container has no information about dependency of %s class and with %s name", baseType, name));
let's move string constants into Constants class

2023-10-30 14:20 UTC, ivlytvynets commented on src/main/java/com/example/di/DiContainer.java
> +                    String.format("Unable to instantiate dependee. Container doesn't contain %s class metadata or contains more than one records", baseType));
let's move string constants into Constants class

2023-10-30 14:20 UTC, ivlytvynets commented on src/main/java/com/example/di/DiContainer.java
> +                throw new ConflictDependencyException("More than one instance of " + baseType + " was found. Use @Qualifier to define exact instance which you want to inject");
let's move string constants into Constants class

2023-10-30 14:20 UTC, ivlytvynets commented on src/main/java/com/example/exception/DependencyRegisteredException.java
> +        super(String.format("Dependency with name %s has been already registered", dependencyName));
let's move string constants into Constants class

2023-10-30 17:03 UTC, AndriyBosik commented on src/main/java/com/example/di/DiContainer.java
> +        if (name == null && baseDiMap.size() != 1) {
extracted condition to `boolean isSingle` variable

2023-10-30 17:04 UTC, AndriyBosik commented on src/main/java/com/example/di/DiContainer.java
> +                            "Unable to instantiate dependee of class %s. No unique primary constructor was found. Consider using %s annotation only once!",
discussed

2023-10-30 17:04 UTC, AndriyBosik commented on src/main/java/com/example/di/DiContainer.java
> +                        String.format("Unable to instantiate dependee. Container has no information about dependency of %s class and with %s name", baseType, name));
discussed

2023-10-30 17:04 UTC, AndriyBosik commented on src/main/java/com/example/di/DiContainer.java
> +                    String.format("Unable to instantiate dependee. Container doesn't contain %s class metadata or contains more than one records", baseType));
discussed

2023-10-30 17:04 UTC, AndriyBosik commented on src/main/java/com/example/di/DiContainer.java
> +                throw new ConflictDependencyException("More than one instance of " + baseType + " was found. Use @Qualifier to define exact instance which you want to inject");
fixed

2023-10-30 17:04 UTC, AndriyBosik commented on src/main/java/com/example/exception/DependencyRegisteredException.java
> +        super(String.format("Dependency with name %s has been already registered", dependencyName));
fixed

2023-11-01 18:05 UTC, ivlytvynets approved these changes

2023-11-01 18:16 UTC, merged