[SW-5] Implement MigrationBuilder interface
AndriyBosik/schema-wizard pull request #3
Opened 2023-10-24 12:30 UTC by AndriyBosik

2023-10-28 11:36 UTC, NikolayProkopchuk commented on src/main/java/com/example/migration/builder/operation/CreateTable.java
> +        return this.compositePrimaryKey(null, obj -> List.of(primaryKeyFunc.apply(obj)));
Can we do  here and in similar places something  like this
return this.compositePrimaryKey(null, obj -> List.of(Objects.requireNonNull(primaryKeyFunc).apply(obj)));
to get rid of first line. What do you think?

2023-10-28 13:17 UTC, NikolayProkopchuk commented on src/main/java/com/example/migration/operation/Operation.java
Can we create AbstractOperation and move there some common logic, like schema and table ...?

2023-10-28 13:17 UTC, NikolayProkopchuk commented on src/main/java/com/example/migration/builder/column/ColumnBuilder.java
Can we add AbstractColumnBuilder like
public abstract class AbstractColumnBuilder implements ColumnBuilder {
    protected final String schema;
    protected final String table;
    protected final String name;
    protected boolean nullable = true;
    protected Boolean defaultValue;

    AbstractColumnBuilder(String schema, String table, String name) {
        this.schema = schema;
        this.table = table;
        this.name = name;
    }

    public AbstractColumnBuilder nullable(boolean nullable) {
        this.nullable = nullable;
        return this;
    }

    public AbstractColumnBuilder defaultValue(boolean defaultValue) {
        this.defaultValue = defaultValue;
        return this;
    }
}

2023-10-28 13:17 UTC, NikolayProkopchuk commented on src/main/java/com/example/migration/builder/operation/OperationBuilder.java
Can we create AbstractOperationBuilder and put there common logic, like schema, table?

2023-10-28 18:25 UTC, AndriyBosik commented on src/main/java/com/example/migration/model/MigrationContext.java
`MigrationContext` is used as an argument to `Migration.up()`, `Migration.down()` methods

2023-10-28 18:41 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/column/ColumnBuilder.java
In this case if I wanna create another builder:
```
public IntegerColumnBuilder {
    ...
    ...

    public TextColumnBuilder maxLength(int maxLength) {
        this.maxLength = maxLength;
        return this;
    }
}
```

But I'll be unable to use it like this
```
TextColumnBuilder.builder("public", "users", "first_name")
    .nullable(true)
    .maxLength(100) // Compilation error because previous line returns an instance of AbstractColumnBuilder instead of TextColumnBuilder
```
And in order to bypass this limitation I must override each method like this:
```
@Override
public TestColumnBuilder table(String table) {
    return this;
}
```
Which makes usage of `AbstractColumnBuilder` quite painful, from my perspective

2023-10-28 18:43 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/operation/OperationBuilder.java
The same as above

2023-10-28 18:52 UTC, AndriyBosik commented on src/main/java/com/example/migration/operation/Operation.java
We have `NativeQueryFileOperation`, `NativeQueryRawOperation` and `CompositeOperation` which don't have schema and table
But I created `abstract class TableBasedOperation` for operations with schema and table properties

2023-10-28 18:56 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/operation/CreateTable.java
> +        return this.compositePrimaryKey(null, obj -> List.of(primaryKeyFunc.apply(obj)));
I also thought about this, but it makes code hard to read, from my perspective
Also, in case of NPE, stack trace will point to exact line where the exception occured if we don't merge this code into one line

2023-10-28 18:59 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/operation/CreateTable.java
> +    public Operation build() {
yeah, good idea, fixed

2023-10-29 07:08 UTC, NikolayProkopchuk commented on src/main/java/com/example/migration/builder/operation/CreateTable.java
> +        return this.compositePrimaryKey(null, obj -> List.of(primaryKeyFunc.apply(obj)));
make sense

2023-10-29 07:16 UTC, NikolayProkopchuk approved these changes

2023-10-30 14:30 UTC, ivlytvynets requested changes

2023-10-30 14:30 UTC, ivlytvynets commented on src/main/java/com/example/migration/builder/operation/CreateTable.java
> +            throw new InvalidMigrationMetadataException("Duplicate primary key definition");
string constant

2023-10-30 14:30 UTC, ivlytvynets commented on src/main/java/com/example/migration/builder/operation/NativeQuery.java
> +            throw new InvalidMigrationMetadataException("Native query migration is empty");
string constant

2023-10-30 17:28 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/column/BoolColumnBuilder.java
> +                "boolean",
extracted

2023-10-30 17:28 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/column/DoubleColumnBuilder.java
> +                "double",
fixed

2023-10-30 17:28 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/column/IntegerColumnBuilder.java
> +                "integer",
fixed

2023-10-30 17:28 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/column/TextColumnBuilder.java
> +                "text",
fixed

2023-10-30 17:28 UTC, AndriyBosik commented on src/main/java/com/example/migration/builder/operation/CreateTable.java
> +            throw new InvalidMigrationMetadataException("Duplicate primary key definition");
fixed

2023-11-01 18:09 UTC, ivlytvynets approved these changes

2023-11-01 18:23 UTC, merged