SW-2 | Implement migration analyzer
AndriyBosik/schema-wizard pull request #4
Opened 2023-10-24 13:53 UTC by NikolayProkopchuk

2023-10-24 15:02 UTC, AndriyBosik commented on src/main/java/com/schemawizard/analyzer/impl/PostgresHistoryTableCreator.java
> +            "WHERE table_schema='public' AND table_type='BASE TABLE' AND table_name='migration_history';";
what if application uses schema different from `public`? Or user doesn't have access to `public` schema
Consider inject `ConfigurationProperties` class and use `defaultSchema` property

2023-10-24 15:42 UTC, NikolayProkopchuk commented on build.gradle
> +    implementation "com.google.guava:guava:${guavaVersion}"
I use this library in ClassesMigrationService in method getMigrations() to get all classes migration, but maybe we can use different approach

2023-10-24 15:48 UTC, NikolayProkopchuk commented on src/main/java/com/schemawizard/analyzer/impl/ClassesMigrationService.java
> +                    .collect(Collectors.toList());
this service returns all classes migrations, MigrationAnalizer filter not applied and returns them

2023-10-26 11:59 UTC, AndriyBosik commented on build.gradle
> +    implementation "com.google.guava:guava:${guavaVersion}"
take a look at `Reflections` library as discussed in Slack

2023-10-30 11:15 UTC, ivlytvynets requested changes

2023-11-01 18:10 UTC, ivlytvynets approved these changes

2023-11-04 19:49 UTC, AndriyBosik requested changes

2023-11-04 19:49 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/impl/PostgresHistoryTableCreator.java
> +            "WHERE table_type='BASE TABLE' AND table_name='migration_history';";
Would you mind using AbstractFactory pattern like this:
```
public interface HistoryTableQueryFactory {
  String getCreateMigrationHistoryTableSql();
  String getSelectTableSql();
  String getSelectMigrationsSql();
  ...
}

public class PostgresHistoryTableQueryFactory implements HistoryTableQueryFactory {
  // Implementations
}

public class OracleHistoryTableQueryFactory implements HistoryTableQueryFactory {
  // Implementations
}
```
And then, in `SchemaWizardBuilder` we can register in our DI container relevant instance of `HistoryTableQueryFactory` interface based on configuration properties.

And this class might be renamed to `HistoryTableCreatorImpl` with `HistoryTableQueryFactory` as a dependency.

2023-11-04 19:49 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/service/impl/PostgresAppliedMigrationsService.java
> +            "FROM migration_history;";
The same as above

2023-11-04 19:49 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/service/impl/ClassesDeclaredMigrationService.java
> +    }
Not sure whether our DI container is able to handle String-injection - check it, please
And if it's not able to do this - inject ConfigurationProperties instance

2023-11-04 19:49 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/service/impl/ClassesDeclaredMigrationService.java
> +        String description = matcher.group(2);
We also have `@com.example.migration.annotation.SWName` annotation which might be use to declare "custom" migration description. So the correct logic to extract description is:
1. Check if @SWName annotation is present on Migration class
2. If @SWName annotation is present - use description from this annotation
3. If @SWName annotation is absent - use description from Migration classname

2023-11-04 19:49 UTC, AndriyBosik commented on src/main/java/com/example/dao/ConnectionHolder.java
> +    }
Not sure whether our DI container is able to handle String injection - check it, please
And if it's not able to do this - inject ConfigurationProperties instance

2023-11-04 19:49 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/impl/MigrationAnalyzerImpl.java
> +    }
In the `AppliedMigrationService.getAppliedMigration()` method, migrations are fetched using this query:
`SELECT id, version, description, applied_on FROM migration_history` -> no ordering was defined and a database might return migrations in any order.
Also, what if a database contains records with versions: 
```
1699126653450
1699126653460
1699126653480
1699126653490
```
And locally user has versions:
```
1699126653450
1699126653460
1699126653470 - new migration
1699126653480
1699126653490
```
This is a possible situation during team work - I can explain it on a call. And does your MigrationAnalyzer is able to handle this case?

2023-11-04 19:49 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/AppliedMigration.java
> +    private final LocalDateTime appliedOn;
Empty lines are redundant. Remove them from everywhere, please

2023-11-05 14:42 UTC, NikolayProkopchuk commented on src/main/java/com/example/analyzer/service/impl/ClassesDeclaredMigrationService.java
> +    }
ConfigurationProperties.packages is used to specify packages for migrations, so migrations can be located in several packages, or this property is used for another purpose?

2023-11-05 14:48 UTC, NikolayProkopchuk commented on src/main/java/com/example/analyzer/impl/MigrationAnalyzerImpl.java
> +    }
MigrationAnalyzer is not able to handle this case yet, maybe logic should be like revert 1699126653480, 1699126653490 and then return 1699126653470 , 1699126653480, 1699126653490 to execute?

2023-11-05 21:20 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/service/impl/ClassesDeclaredMigrationService.java
> +    }
Currently we don't have any "strict" rules for configuration properties. I defined `packages` as `List` just for example of using lists in yaml file.
So feel free to change it to plain `String` if it's easier for you. But, in this case, do not forget to update `ConfigurationPropertiesServiceImpl.mapConfigurationProperties()` method

2023-11-05 21:30 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/impl/MigrationAnalyzerImpl.java
> +    }
I don't think it's a good solution to revert migration without a user to be asked for. My suggestion is to define `declaredMigrations` like the following:
```
Map<Integer, DeclaredMigration> declaredMigrations = declaredMigrationService.getDeclaredMigrations().stream()
  .collect(
    Collectors.toMap(
      DeclaredMigration::getVersion,
      Function.identity()));
```
And implement comparison:
```
for (AppliedMigration migration: appliedMigrations) {
  if (!declaredMigrations.containsKey(migration.getVersion())) {
    throw new MigrationAnalyzerException("Migration with version " + migration.getVersion() + " was not found");
  }
  declaredMigrations.remove(migration.getVersion());
}
```
Finally, return:
```
return declaredMigrations.values().stream()
  .sorted() // define sorting logic based on migration version
  .collect(Collectors.toList());
```

2023-11-08 09:16 UTC, AndriyBosik requested changes

2023-11-08 09:16 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/DeclaredMigration.java
> +public class DeclaredMigration implements Comparable<DeclaredMigration> {
wouldn't it be better to extract this to a separate class or utility class?

2023-11-08 09:16 UTC, AndriyBosik commented on src/main/java/com/example/analyzer/impl/PostgresHistoryTableCreator.java
> +}
Use PostgresHistoryTableQueryFactory here, please

2023-11-08 09:24 UTC, NikolayProkopchuk commented on src/main/java/com/example/analyzer/impl/PostgresHistoryTableCreator.java
> +}
sorry, forgot to delete this class, it is not used now)

2023-11-09 09:14 UTC, AndriyBosik requested changes

2023-11-09 09:14 UTC, AndriyBosik commented on src/main/resources/application.yaml
> +      packageName: com.example.db.migration
use `package-name` to follow the same convention

2023-11-09 09:20 UTC, AndriyBosik approved these changes

2023-11-20 10:32 UTC, ivlytvynets approved these changes

2023-11-21 08:04 UTC, merged