[SW-6] Implement SchemaWizard runner
AndriyBosik/schema-wizard pull request #7
Opened 2023-12-04 15:30 UTC by AndriyBosik

2023-12-11 11:33 UTC, NikolayProkopchuk approved these changes

2023-12-15 20:41 UTC, ivlytvynets requested changes

2023-12-15 20:41 UTC, ivlytvynets commented on schema-wizard-core/src/main/java/org/schemawizard/core/dao/impl/TransactionServiceImpl.java
> +        }
try with resources, move to separate private method

2023-12-15 20:41 UTC, ivlytvynets commented on schema-wizard-core/src/main/java/org/schemawizard/core/migration/service/impl/OperationResolverServiceImpl.java
> +                        }));
move into init() method to improve visibility

2023-12-15 20:47 UTC, AndriyBosik commented on schema-wizard-core/src/main/java/org/schemawizard/core/dao/impl/TransactionServiceImpl.java
> +        }
unable to use try with resources
![image](https://github.com/AndriyBosik/schema-wizard/assets/55958195/6d5f9f7c-b8d2-494e-b306-b5a6b6c05eba)

2023-12-15 21:19 UTC, AndriyBosik commented on schema-wizard-core/src/main/java/org/schemawizard/core/dao/impl/TransactionServiceImpl.java
> +        }
moved to separate method

2023-12-15 21:20 UTC, AndriyBosik commented on schema-wizard-core/src/main/java/org/schemawizard/core/migration/service/impl/OperationResolverServiceImpl.java
> +                        }));
extracted to another method

2023-12-29 13:20 UTC, ivlytvynets approved these changes

2023-12-29 13:27 UTC, merged